name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Aptitude Dependencies
      run: |
        apt update
        apt install git cmake build-essential lsb-core
