name: Ubuntu Native Build CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Aptitude Dependencies
      run: |
        apt -o APT::Sandbox::User=root update
        apt install git cmake build-essential lsb-core
